apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx/nginx-service.yaml
  - nginx/nginx-depl.yaml
  - db/db-service.yaml
  - db/db-config.yaml
  - db/db-depl.yaml
  - message-broker/rabbitmq-depl.yaml
  - message-broker/rabbitmq-service.yaml
  - message-broker/rabbitmq-config.yaml
